# Generated by Django 5.1.11 on 2025-06-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_simbol"),
    ]

    operations = [
        migrations.RenameField(
            model_name="simbol",
            old_name="cod_imagine",
            new_name="id_imagine",
        ),
        migrations.AddField(
            model_name="simbol",
            name="descriere",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="simbol",
            name="regiuni",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="simbol",
            name="semnificatie",
            field=models.TextField(default=""),
        ),
    ]
